Listy business
spianoDev/fhlbc-collaboration pull request #5
Opened 2023-04-28 15:44 UTC by ashleyann9535

2023-04-28 15:52 UTC, jkapnick requested changes
Please update variables i and l in line 18 to be more descriptive.

2023-05-02 00:31 UTC, ashleyann9535 commented
Variables have been updated and comments have been added.

2023-05-05 15:22 UTC, jkapnick commented
Code changes look good.  Variables updated and comments added

2023-05-05 15:24 UTC, jkapnick approved these changes

2023-05-05 15:25 UTC, merged